#!/bin/sh
#deploy="false"
deploy="true"

image=test15
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t test/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push test/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag test/${image}:1.0-SNAPSHOT test/${image}:latest
        docker push test/${image}:latest
    fi
fi